name: Web App CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths: ["./packages/web-app/**.tsx"]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/web-app
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./yarn.lock"
      - run: npm install yarn
      - run: npx yarn install
      - run: npx yarn lint:check
